### ISSUE TITLE
Issue while importing the chart

### ISSUE THREAD

**Issue by imranece59** [ZEPL/zeppelin-ultimate-pie-chart#1]
Hi,

I am getting the below error while importing the chart into zeppelin

   /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.json doesn't exist
      resolve directory
        /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation doesn't exist (directory default file)
        /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation/package.json doesn't exist (directory description file)
[/opt/zeppelin-0.7.1-bin-all/node_modules/zeppelin-tabledata]
[/opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation]
[/opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.webpack.js]
[/opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.web.js]
[/opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.js]
[/opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.json]
 @ ./~/ultimate-pie-chart/index.js 15:30-83
java.io.IOException: ./~/ultimate-pie-chart/index.js
Module not found: Error: Cannot resolve module 'zeppelin-tabledata/advanced-transformation' in /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/ultimate-pie-chart
resolve module zeppelin-tabledata/advanced-transformation in /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/ultimate-pie-chart
  looking for modules in /opt/zeppelin-0.7.1-bin-all/node_modules
    /opt/zeppelin-0.7.1-bin-all/node_modules/zeppelin-tabledata doesn't exist (module as directory)
  looking for modules in /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules
    resolve 'file' or 'directory' advanced-transformation in /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata
      resolve file
        /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation doesn't exist
        /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.webpack.js doesn't exist
        /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.web.js doesn't exist
        /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.js doesn't exist
        /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.json doesn't exist
      resolve directory
        /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation doesn't exist (directory default file)
        /opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation/package.json doesn't exist (directory description file)
[/opt/zeppelin-0.7.1-bin-all/node_modules/zeppelin-tabledata]
[/opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation]
[/opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.webpack.js]
[/opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.web.js]
[/opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.js]
[/opt/zeppelin-0.7.1-bin-all/local-repo/vis/node_modules/zeppelin-tabledata/advanced-transformation.json]
 @ ./~/ultimate-pie-chart/index.js 15:30-83
	at org.apache.zeppelin.helium.HeliumVisualizationFactory.bundle(HeliumVisualizationFactory.java:265)
	at org.apache.zeppelin.helium.HeliumVisualizationFactory.bundle(HeliumVisualizationFactory.java:114)
	at org.apache.zeppelin.helium.Helium.enable(Helium.java:223)
	at org.apache.zeppelin.rest.HeliumRestApi.enablePackage(HeliumRestApi.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.

zeppelin-tabledata/advanced-transformation is not available from npm. I see only zeppelin-advanced-transformation. Same issue for other ultimate charts import as well.

Please let me know the workaround.

**Comment by AhyoungRyu** [comment]
Hi @imranece59. Thanks for sharing your issue. 

Seems you're using Zeppelin 0.7.1 ver. Unfortunately `zeppelin-ultimate-pie-chart` is only available from 0.8.0-SNAPSHOT version as described in here https://github.com/ZEPL/zeppelin-ultimate-pie-chart#compatibility
